### ISSUE TITLE
The Github link on Hex.pm is pointing to another package

### ISSUE THREAD

**Issue by mindreframer** [mworrell/s3filez#13]
FYI: on https://hex.pm/packages/s3filez

 -> Clicking "Github" leads to https://github.com/zotonic/template_compiler

It took me a while to find the right Github repo. 

Thanks for this lean S3 alternative, the only other option is https://hex.pm/packages/ex_aws with a bunch of dependencies.

**Comment by mworrell** [comment]
Thanks!  I think you can guess which project I used as a template....

**Comment by mworrell** [comment]
And indeed, I just needed a simple file interface to s3, not the whole kitchen sink.
And it needed to be able to stream results, which seems to be missing in other clients.

**Comment by mindreframer** [comment]
Thanks for the quickfix!
